export const candidates = [
  {
    name: 'Manohar Lal',
    party: 'Bharatiya Janata Party',
    status: 'Lead',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Divyanshu Budhiraja',
    party: 'Indian National Congress',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Inder Singh',
    party: 'Bahujan Samaj Party',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Maratha Virender Verma',
    party: 'Nationalist Congress Party - Sharadchandra Pawar',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Devender Kadian',
    party: 'Jannayak Janta Party',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Manoj Bansal',
    party: 'Independent',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Gulshan Kashyap',
    party: 'Independent',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Ashok Kataria',
    party: 'Samst Samaj Party',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Harjeet Singh Virk',
    party: 'Shiromani Akali Dal (Amritsar)(Simranjit Singh Mann)',
    status: 'Trail',
    stateId: 14,
    cityId: 6,
  },
  {
    name: 'Naveen Jindal',
    party: 'Bharatiya Janata Party',
    status: 'Won',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Dr Sushil Gupta',
    party: 'Aam Aadmi Party',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Abhay Singh Chautala',
    party: 'Indian National Lok Dal',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Deepak Mehra',
    party: 'Bahujan Samaj Party',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Jai Kumar Saini Hamidpur',
    party: 'Independent',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Pala Ram Saini',
    party: 'Jannayak Janta Party',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Satbir Kashyap',
    party: 'Rashtriya Janshakti Party (Eklavya)',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Khazan Singh Sehgal',
    party: 'Shiromani Akali Dal (Amritsar) (Simranjit Singh Mann)',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
  {
    name: 'Mahavir Singh',
    party: 'Ekam Sanatan Bharat Dal',
    status: 'Lost',
    stateId: 14,
    cityId: 40,
  },
]
