export const states = [
  {
    id: 1,
    state: 'Maharashtra',
    hindi: 'महाराष्ट्र',
    city_count: 129,
    short_code: 'MA',
  },
  {
    id: 2,
    state: 'Delhi',
    hindi: 'दिल्ली',
    city_count: 2,
    short_code: 'DE',
  },
  {
    id: 3,
    state: 'Karnataka',
    hindi: 'कर्नाटक',
    city_count: 91,
    short_code: 'KA',
  },
  {
    id: 4,
    state: 'Gujarat',
    hindi: 'गुजरात',
    city_count: 75,
    short_code: 'GU',
  },
  {
    id: 5,
    state: 'Telangana',
    hindi: 'तेलंगाना',
    city_count: 41,
    short_code: 'TE',
  },
  {
    id: 6,
    state: 'Tamil Nadu',
    hindi: 'तमिलनाडु',
    city_count: 115,
    short_code: 'TN',
  },
  {
    id: 7,
    state: 'West Bengal',
    hindi: 'पश्चिम बंगाल',
    city_count: 52,
    short_code: 'WB',
  },
  {
    id: 8,
    state: 'Rajasthan',
    hindi: 'राजस्थान',
    city_count: 83,
    short_code: 'RA',
  },
  {
    id: 9,
    state: 'Uttar Pradesh',
    hindi: 'उत्तर प्रदेश',
    city_count: 129,
    short_code: 'UP',
  },
  {
    id: 10,
    state: 'Bihar',
    hindi: 'बिहार',
    city_count: 73,
    short_code: 'BI',
  },
  {
    id: 11,
    state: 'Madhya Pradesh',
    hindi: 'मध्य प्रदेश',
    city_count: 87,
    short_code: 'MP',
  },
  {
    id: 12,
    state: 'Andhra Pradesh',
    hindi: 'आंध्र प्रदेश',
    city_count: 83,
    short_code: 'AP',
  },
  {
    id: 13,
    state: 'Punjab',
    hindi: 'पंजाब',
    city_count: 56,
    short_code: 'PU',
  },
  {
    id: 14,
    state: 'Haryana',
    hindi: 'हरियाणा',
    city_count: 40,
    short_code: 'HA',
  },
  {
    id: 15,
    state: 'Jammu and Kashmir',
    hindi: 'जम्मू और कश्मीर',
    city_count: 9,
    short_code: 'JAK',
  },
  {
    id: 16,
    state: 'Jharkhand',
    hindi: 'झारखंड',
    city_count: 30,
    short_code: 'JH',
  },
  {
    id: 17,
    state: 'Chhattisgarh',
    hindi: 'छत्तीसगढ़',
    city_count: 19,
    short_code: 'CH',
  },
  {
    id: 18,
    state: 'Assam',
    hindi: 'असम',
    city_count: 25,
    short_code: 'AS',
  },
  {
    id: 19,
    state: 'Chandigarh',
    hindi: 'चंडीगढ़',
    city_count: 1,
    short_code: 'CH',
  },
  {
    id: 20,
    state: 'Odisha',
    hindi: 'ओडिशा',
    city_count: 38,
    short_code: 'OD',
  },
  {
    id: 21,
    state: 'Kerala',
    hindi: 'केरल',
    city_count: 55,
    short_code: 'KE',
  },
  {
    id: 22,
    state: 'Uttarakhand',
    hindi: 'उत्तराखंड',
    city_count: 19,
    short_code: 'UT',
  },
  {
    id: 23,
    state: 'Puducherry',
    hindi: 'पुदुचेरी',
    city_count: 4,
    short_code: 'PU',
  },
  {
    id: 24,
    state: 'Tripura',
    hindi: 'त्रिपुरा',
    city_count: 7,
    short_code: 'TR',
  },
  {
    id: 25,
    state: 'Mizoram',
    hindi: 'मिज़ोरम',
    city_count: 3,
    short_code: 'MI',
  },
  {
    id: 26,
    state: 'Meghalaya',
    hindi: 'मेघालय',
    city_count: 3,
    short_code: 'ME',
  },
  {
    id: 27,
    state: 'Manipur',
    hindi: 'मणिपुर',
    city_count: 4,
    short_code: 'MA',
  },
  {
    id: 28,
    state: 'Himachal Pradesh',
    hindi: 'हिमाचल प्रदेश',
    city_count: 7,
    short_code: 'HP',
  },
  {
    id: 29,
    state: 'Nagaland',
    hindi: 'नागालैंड',
    city_count: 6,
    short_code: 'NA',
  },
  {
    id: 30,
    state: 'Goa',
    hindi: 'गोवा',
    city_count: 4,
    short_code: 'GO',
  },
  {
    id: 31,
    state: 'Andaman and Nicobar Islands',
    hindi: 'अंडमान और निकोबार द्वीप समूह',
    city_count: 1,
    short_code: 'AANI',
  },
  {
    id: 32,
    state: 'Arunachal Pradesh',
    hindi: 'अरुणाचल प्रदेश',
    city_count: 3,
    short_code: 'AP',
  },
  {
    id: 33,
    state: 'Dadra and Nagar Haveli',
    hindi: 'दादरा और नगर हवेली',
    city_count: 1,
    short_code: 'DANH',
  },
  {
    id: 34,
    state: 'Sikkim',
    hindi: 'सिक्किम',
    city_count: 1,
    short_code: 'SK',
  },
]
